### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by YoushaaMurhij** [SmartBot-PJLab/P3Former#1]
Hi, Thanks for sharing this great work!
Could you please estimate the code release date?
Thanks

**Comment by xizaoqu** [comment]
Thanks for your interest in our work.
If all things go well, the code is expected to be released in about a month.

**Comment by xizaoqu** [comment]
> Hi, Thanks for sharing this great work! Could you please estimate the code release date? Thanks


We have released the codes and models. Feel free to try them out!
