### ISSUE TITLE
Reproduce the baseline result

### ISSUE THREAD

**Issue by hphnngcquan** [SmartBot-PJLab/P3Former#10]
Hi Authors,

Thank you for this good work.

I am trying to reproduce the results of the baseline on the SemanticKITTI validation set as below:
![image](https://github.com/OpenRobotLab/P3Former/assets/106338986/492138f3-7ff6-498b-a744-3fbbceae6b52)

How can i config in the code to train the baseline model?

I saw that i need to set the pe_type and use_pa_seg flags in the decoder configuration, is that all?

Thank you

**Comment by xizaoqu** [comment]
Yes, and we use MFA by default, which does not generate a mask from query and key.

**Comment by hphnngcquan** [comment]
> Yes, and we use MFA by default, which does not generate a mask from query and key.


Thanks for your reply
So if i disable pa_seg, and do not specify pe_type in decoder head, MFA will be changed to normal cross attention like the vanilla segmentor, is it correct?

**Comment by xizaoqu** [comment]
So if i disable pa_seg, and do not specify pe_type in decoder head, MFA will be changed to normal cross attention like the vanilla segmentor, is it correct?

Nope, it will still use the mask. I do not implement vanilla cross-attention here.

**Comment by hphnngcquan** [comment]
ok, thanks for your reply
