### ISSUE TITLE
Ask about paper

### ISSUE THREAD

**Issue by hphnngcquan** [SmartBot-PJLab/P3Former#11]
Dear @xizaoqu 
Thank you for this excellent work

I am working on your research and want to improve it
I want to make several comparisons with your results, can you please give me the sequence and scan number of the below hard cases and failure cases?
![image](https://github.com/OpenRobotLab/P3Former/assets/106338986/5d93ec3c-06e1-4abd-b1e9-2f181899f191)

Regards

**Comment by xizaoqu** [comment]
Hi, sorry I didn't save the scan number. However, it is not hard to find such cases in the SemanticKITTI dataset.

**Comment by hphnngcquan** [comment]
> Hi, sorry I didn't save the scan number. However, it is not hard to find such cases in the SemanticKITTI dataset.

Thank you for your reply
