### ISSUE TITLE
Visualization scripts?

### ISSUE THREAD

**Issue by xushilin1** [SmartBot-PJLab/P3Former#3]
Thanks for sharing your excellent open-source code. 
I am highly interested in your work and would like to use it for visualization purposes. Can you provide me with a script or tutorial on how to visualize the point cloud? 
Thank you very much.

**Comment by xizaoqu** [comment]
> Thanks for sharing your excellent open-source code. I am highly interested in your work and would like to use it for visualization purposes. Can you provide me with a script or tutorial on how to visualize the point cloud? Thank you very much.

What type of visualization do you need? You can refer to https://github.com/PRBonn/semantic-kitti-api. Most of the figures in my paper are made by this tool.

**Comment by xushilin1** [comment]
Thank you for your time, and it helps me a lot.
