### ISSUE TITLE
Code about nuScenes

### ISSUE THREAD

**Issue by WeijianZhang123** [SmartBot-PJLab/P3Former#4]
Thanks your nice work! Do you have any plans to release nuScenes code?

**Comment by xizaoqu** [comment]
Thanks for your interest in our project. We are still refactoring our code for nuScenes. If you really want to train the model on nuScenes, you can refer to https://github.com/open-mmlab/mmdetection3d/blob/main/projects/TPVFormer/tpvformer/nuscenes_dataset.py. It includes basic elements for nuScenes semantic segmentation. You can modify it to a panoptic one.

**Comment by WeijianZhang123** [comment]
Thanks, that helps a lot!
And I have another question: For training and evaluation in nuScenes, are the semantic labels directly obtained from 'lidarseg' labels or from the semantic part of 'panoptic' labels?

**Comment by WeijianZhang123** [comment]
> 

I have found the answer is 'panoptic', from loading.py.
