### ISSUE TITLE
nuScenes Code

### ISSUE THREAD

**Issue by RONINGOD** [SmartBot-PJLab/P3Former#9]
![image](https://github.com/OpenRobotLab/P3Former/assets/81010418/a9249491-fd67-4314-b317-3ec372f7d73c)
Why are the weights calculated but not used when computing the loss?

**Comment by xizaoqu** [comment]
Hi, do you mean the ``avg_factor`` variable? If so, it's just because I do not clean it up.

**Comment by RONINGOD** [comment]
> Hi, do you mean the `avg_factor` variable? If so, it's just because I do not clean it up.

![image](https://github.com/OpenRobotLab/P3Former/assets/81010418/ad10f48a-b7db-4a83-9d36-235aac414f71)
No, what I mean is that you sample the matched label_weight and mask_weight, but they are not used when calculating the cls_loss. Is it because using them does not work well on the nuScenes dataset? In the version you used on the SemanticKITTI dataset, did you use them?

**Comment by xizaoqu** [comment]
Hi, If I remember correctly it's optional as the effects are marginal. I use the ``label_weight`` in SemanticKITTI which makes the results slightly better. https://github.com/OpenRobotLab/P3Former/blob/main/p3former/decode_heads/p3former_head.py#L533

**Comment by RONINGOD** [comment]
> Hi, If I remember correctly it's optional as the effects are marginal. I use the `label_weight` in SemanticKITTI which makes the results slightly better. https://github.com/OpenRobotLab/P3Former/blob/main/p3former/decode_heads/p3former_head.py#L533

Thank you!
